%% Diagrama de Casos de Uso para as Histórias de Usuário
%%{ init: { 'theme': 'default' } }%%
%%{flowchart}%%
graph TD

Funcionario[Funcionario]

subgraph CasosDeUso
    UC1["Cadastrar Placa de Veículo"]
    UC2["Consultar Placas Cadastradas"]
    UC3["Consultar Vagas Disponíveis"]
    UC4["Consultar Tempo de Permanência e Saldo"]
    UC5["Consultar Planos de Fidelidade"]
end

Funcionario --> UC1
Funcionario --> UC2
Funcionario --> UC3
Funcionario --> UC4
Funcionario --> UC5
